### ISSUE TITLE
MovieMator 2.6.2 address sanitizer测试资源库视频修改轨道属性过程中崩溃

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#509]
资源库视频clip，修改属性->高级->轨道改为无->预览视频->再将轨道改为原来的值。崩溃。

**代码**
![屏幕快照 2019-07-08 下午5 40 36](https://user-images.githubusercontent.com/48675877/60800285-884f0080-a1a7-11e9-8367-704f893c224f.png)

**详细报告**

==16668==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001072b43b8 bp 0x7ffeec522bf0 sp 0x7ffeec522bc0 T0)
==16668==The signal is caused by a READ memory access.
==16668==Hint: address points to the zero page.
#0 0x1072b43b7 in Mlt::Properties::set(char const*, int) MltProperties.cpp:164
#1 0x1038c19be in AvformatProducerWidget::reopen(Mlt::Producer*) avformatproducerwidget.cpp:137
#2 0x1038ccfb7 in AvformatProducerWidget::on_okButton_clicked() avformatproducerwidget.cpp:536
#3 0x103d2207d in AvformatProducerWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) moc_avformatproducerwidget.cpp:160
#4 0x103d22c4c in AvformatProducerWidget::qt_metacall(QMetaObject::Call, int, void**) moc_avformatproducerwidget.cpp:227
#5 0x1083965d8 in QMetaObject::activate(QObject*, int, int, void**) (QtCore:x86_64+0x2175d8)
#6 0x10756a00f in QAbstractButtonPrivate::emitClicked() (QtWidgets:x86_64+0xfe00f)
#7 0x107569e93 in QAbstractButtonPrivate::click() (QtWidgets:x86_64+0xfde93)
#8 0x10756af0d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) (QtWidgets:x86_64+0xfef0d)
#9 0x1074bee17 in QWidget::event(QEvent*) (QtWidgets:x86_64+0x52e17)
#10 0x10756ac5e in QAbstractButton::event(QEvent*) (QtWidgets:x86_64+0xfec5e)
#11 0x10747dec5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (QtWidgets:x86_64+0x11ec5)
#12 0x10748179c in QApplication::notify(QObject*, QEvent*) (QtWidgets:x86_64+0x1579c)
#13 0x108362f23 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (QtCore:x86_64+0x1e3f23)
#14 0x10747e897 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) (QtWidgets:x86_64+0x12897)
#15 0x1074e0226 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (QtWidgets:x86_64+0x74226)
#16 0x1074df210 in QWidgetWindow::event(QEvent*) (QtWidgets:x86_64+0x73210)
#17 0x10747dec5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (QtWidgets:x86_64+0x11ec5)
#18 0x107480984 in QApplication::notify(QObject*, QEvent*) (QtWidgets:x86_64+0x14984)
#19 0x108362f23 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (QtCore:x86_64+0x1e3f23)
#20 0x107b77989 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (QtGui:x86_64+0x27989)
#21 0x107b60cfa in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (QtGui:x86_64+0x10cfa)
#22 0x10ef0db60 in QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) (libqcocoa.dylib:x86_64+0x23b60)
#23 0x7fff529ee128 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (CoreFoundation:x86_64+0x58128)
#24 0x7fff529ee0ce in __CFRunLoopDoSource0 (CoreFoundation:x86_64+0x580ce)
#25 0x7fff529d1f6f in __CFRunLoopDoSources0 (CoreFoundation:x86_64+0x3bf6f)
#26 0x7fff529d1516 in __CFRunLoopRun (CoreFoundation:x86_64+0x3b516)
#27 0x7fff529d0df9 in CFRunLoopRunSpecific (CoreFoundation:x86_64+0x3adf9)
#28 0x7fff51c5c894 in RunCurrentEventLoopInMode (HIToolbox:x86_64+0xa894)
#29 0x7fff51c5c4d3 in ReceiveNextEventCommon (HIToolbox:x86_64+0xa4d3)
#30 0x7fff51c5c347 in _BlockUntilNextEventMatchingListInModeWithFilter (HIToolbox:x86_64+0xa347)
#31 0x7fff4ff1995a in _DPSNextEvent (AppKit:x86_64+0x1a95a)
#32 0x7fff4ff186f9 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (AppKit:x86_64+0x196f9)
#33 0x7fff50164d69 in -[NSApplication _doModalLoop:peek:] (AppKit:x86_64+0x265d69)
#34 0x7fff503eacd6 in __33-[NSApplication runModalSession:]_block_invoke_2 (AppKit:x86_64+0x4ebcd6)
#35 0x7fff503eac7e in __33-[NSApplication runModalSession:]_block_invoke (AppKit:x86_64+0x4ebc7e)
#36 0x7fff50162ff7 in _NSTryRunModal (AppKit:x86_64+0x263ff7)
#37 0x7fff503eab74 in -[NSApplication runModalSession:] (AppKit:x86_64+0x4ebb74)
#38 0x10ef0c8f9 in QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (libqcocoa.dylib:x86_64+0x228f9)
#39 0x10835f2f0 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (QtCore:x86_64+0x1e02f0)
#40 0x108363594 in QCoreApplication::exec() (QtCore:x86_64+0x1e4594)
#41 0x1036efdb4 in main main.cpp:591
#42 0x7fff7fb04084 in start (libdyld.dylib:x86_64+0x17084)

==16668==Register values:
rax = 0x0000100000000000 rbx = 0x0000000000000024 rcx = 0x0000000000000000 rdx = 0x000000000000bc1f 
rdi = 0x0000000000000000 rsi = 0x0000000000000000 rbp = 0x00007ffeec522bf0 rsp = 0x00007ffeec522bc0 
r8 = 0x0000000000013000 r9 = 0x0000000000000000 r10 = 0x00006190006c7e30 r11 = 0x00006190006c7e28 
r12 = 0x000060700046d4c0 r13 = 0x00000001086c2be0 r14 = 0x0000000000000000 r15 = 0x0000608000446220 
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV MltProperties.cpp:164 in Mlt::Properties::set(char const*, int)
==16668==ABORTING

**Comment by hpuzj** [comment]
跟测完成。
资源库clip和时间线上的clip，均进行属性中轨道参数的修改，再修改回原来的值，无闪退问题
修改了clip的速度并进行切分，修改属性中的轨道参数，可正常运行。
